services:
  - type: web
    name: itshlp
    env: node
    buildCommand: npm install && pip install -r requirements.txt && npm run build
    startCommand: npm run start
    envVars:
      - key: NODE_VERSION
        value: 18.12.1
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: QDRANT_URL
        value: https://b361537d-20a3-4a84-b96f-9efb19837c15.us-east4-0.gcp.cloud.qdrant.io:6333
      - key: QDRANT_COLLECTION_ZENDESK
        value: ZENDESK
      - key: QDRANT_COLLECTION_JIRA
        value: JIRA
      - key: QDRANT_COLLECTION_CONFLUENCE
        value: CONFLUENCE
      - key: QDRANT_COLLECTION_NETSUITE
        value: NETSUITE
      - key: QDRANT_COLLECTION_NETSUITE_DUMMIES
        value: NETSUITE_DUMMIES
      - key: QDRANT_COLLECTION_SAP
        value: SAP
      - key: QDRANT_API_KEY
        sync: false
      - key: OPENAI_API_KEY
        sync: false