# Fichier de configuration pour le déploiement sur Render
# Version Python pour l'application Qdrant Web

services:
  - type: web
    name: itshlp
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0
      - key: QDRANT_URL
        value: false
      - key: QDRANT_COLLECTION_ZENDESK
        value: ZENDESK
      - key: QDRANT_COLLECTION_JIRA
        value: JIRA
      - key: QDRANT_COLLECTION_CONFLUENCE
        value: CONFLUENCE
      - key: QDRANT_COLLECTION_NETSUITE
        value: NETSUITE
      - key: QDRANT_COLLECTION_NETSUITE_DUMMIES
        value: NETSUITE_DUMMIES
      - key: QDRANT_COLLECTION_SAP
        value: SAP
      - key: QDRANT_API_KEY
        sync: false
      - key: OPENAI_API_KEY
        sync: false
      - key: REDIS_URL
        value: redis://default:ASmFAAIjcDFhZTE4MDU2MzQ0OGE0YTE3OGY5ZDJlMDUxNzVkMGM4NXAxMA@finer-octopus-10629.upstash.io:6379
      - key: DATABASE_URL
  sync: false
    healthCheckPath: /
    autoDeploy: true
