"""create cache tables

Revision ID: 1e326740bc97
Revises: 0001_create_cache_tables
Create Date: 2025-04-10 11:08:14.742289

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1e326740bc97'
down_revision = '0001_create_cache_tables'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cached_formats',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('format_type', sa.String(), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('sources', sa.String(), nullable=True),
    sa.Column('meta', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cached_queries',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('query', sa.Text(), nullable=True),
    sa.Column('filters', sa.JSON(), nullable=True),
    sa.Column('limit', sa.Integer(), nullable=True),
    sa.Column('embedding', sa.Integer(), nullable=True),
    sa.Column('raw_results', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cached_queries')
    op.drop_table('cached_formats')
    # ### end Alembic commands ###
